# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDL-Planet
version:      0.05
version_from: planet.pd
installdirs:  site
requires:
    Image::Size:                   0
    PDL:                           
    PDL::Orbit:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
