--- #YAML:1.0
name:                PDL-Planet
version:             0.12
abstract:            ~
license:             ~
author:              
    - Douglas Hunt (dhunt@ucar.edu)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Image::Size:                   0
    PDL:                           
    PDL::Orbit:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
